import os
import random
import requests
from instagrapi import Client

# =====================================================
# ENV VARIABLES
# =====================================================
IG_USER = os.getenv("INSTA_USER")
IG_PASS = os.getenv("INSTA_PASS")
IG_SESSION = os.getenv("INSTA_SESSION")

# =====================================================
# TOPIC GENERATION (AI SIMULATION – FREE)
# =====================================================
MYSTERY_TOPICS = [
    "The lost city of Agartha beneath the Earth's crust",
    "The disappearance of the USS Cyclops in the Bermuda Triangle",
    "Ancient Sumerians' mysterious star maps",
    "The unsolved incident of Dyatlov Pass",
    "The legend of the Black Knight Satellite",
    "Göbeklitepe's unknown builders",
    "The cursed tombs of Egyptian priests",
    "The missing Mayan golden codex",
    "A mysterious medieval manuscript discovered in Europe",
    "Ghost ships seen drifting without crew"
]

def generate_topic():
    return random.choice(MYSTERY_TOPICS)

# =====================================================
# IMAGE GENERATION — POLLINATIONS
# =====================================================
def generate_image(topic):
    image_url = f"https://image.pollinations.ai/prompt/{topic.replace(' ', '%20')}"
    img_data = requests.get(image_url).content

    filename = "generated.jpg"
    with open(filename, "wb") as f:
        f.write(img_data)

    return filename

# =====================================================
# INSTAGRAM LOGIN
# =====================================================
def insta_login():
    cl = Client()

    if IG_SESSION:
        try:
            cl.load_settings(IG_SESSION)
            cl.login(IG_USER, IG_PASS)
            return cl
        except:
            pass

    cl.login(IG_USER, IG_PASS)
    return cl

# =====================================================
# INSTAGRAM POST
# =====================================================
def post_to_instagram(cl, image_path, caption):
    cl.photo_upload(image_path, caption)
    print("Post uploaded successfully.")

# =====================================================
# MAIN BOT LOGIC
# =====================================================
if __name__ == "__main__":

    if not IG_USER or not IG_PASS:
        raise Exception("INSTA_USER and INSTA_PASS environment variables are missing.")

    print("Logging into Instagram...")
    cl = insta_login()

    print("Generating topic...")
    topic = generate_topic()

    print("Generating image...")
    image_path = generate_image(topic)

    caption = f"""
{topic}

Generated by AI • Mystery & History Series
"""

    print("Posting to Instagram...")
    post_to_instagram(cl, image_path, caption)

    print("Done.")
